### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by radical-squared** [anna-money/asyncpg-listen#153]
Many thanks for sharing and maintaining this valuable project. Is there a way to use the connect_func with a connection from a connection pool?
```
pgpool = await asyncpg.create_pool(dsn=myl_dsn)
async with pgpool.acquire() as connection: 
```

**Comment by Pliner** [comment]
Hi @radical-squared!

>Many thanks for sharing and maintaining this valuable project.

Thanks :)

>Is there a way to use the connect_func with a connection from a connection pool?

Connection pool is not used, because a connection here is long lived. 

Even if a connection pool is used, one connection from the pool will be occupied and will never be returned back, which doesn't look like a good use case for the pool.

**Comment by radical-squared** [comment]
I see. Thanks for explaining that. The code is magic to me, but works like a charm. Happy holidays!
