### ISSUE TITLE
What is the technical need for limiting deployment to Python 3.9 or later?

### ISSUE THREAD

**Issue by enquora** [anna-money/asyncpg-listen#53]
This library requires Python 3.9 or greater, yet asyncpg itself has a supports 3.6 and later.
What is the technical requirement driving this decision (it's not obvious at first glance)?

**Comment by Pliner** [comment]
Hi @enquora,

Sorry for the late response, I missed the notification.

There is no specific reason, we just don't need any other versions, except two recent released major ones. 

PS I've added support of python 3.8.
