### ISSUE TITLE
Running README.md example code gives "AttributeError: __aenter__"

### ISSUE THREAD

**Issue by dfuhry** [anna-money/asyncpg-listen#90]
When I (pip) install asyncpg-listen and try to run the example code in the README.md, I get error "AttributeError: \_\_aenter\_\_" at line "async with asyncpg.connect() as connection:".

I'm running the latest asyncpg, 0.25.0, which doesn't support connections as context managers:
https://github.com/MagicStack/asyncpg/issues/583
so I am not sure how you got the example to work as written.

**Comment by Pliner** [comment]
Hi @dfuhry,

Thanks for raising this. I've fixed README in 16191cd5f4b9f98f1d91f486ea84891914fb385b.
